export const OFFICES = [
  "Angul Bazar S.O",
  "Angul H.O",
  "Anlabereni S.O",
  "Athamallik S.O",
  "Badasuanlo S.O",
  "Bagedia S.O",
  "Balanda S.O",
  "Balimi S.O",
  "Banarpal S.O",
  "Bantala S.O",
  "Bhapur S.O (Dhenkanal)",
  "Bhuban S.O",
  "Chhendipada S.O",
  "Deepasikha S.O",
  "Dera S.O",
  "Deulbera Colliery S.O",
  "Dhenkanal College S.O",
  "Dhenkanal H.O",
  "Dhenkanal R S S.O",
  "Gadasila S.O",
  "Gondiapatna S.O",
  "Gopalprasad S.O",
  "Govindpur S.O (Dhenkanal)",
  "Hakimpada S.O",
  "Hindol Road R.S. S.O",
  "Hindol S.O",
  "Hulurisinga S.O",
  "Igit Sarang S.O",
  "JARAPADA S.O",
  "Jindal Nagar S.O",
  "Jubuli Town S.O",
  "Kamakhyanagar S.O",
  "Kaniha S.O",
  "Kankadahad S.O",
  "Khamar S.O",
  "Kishoreganj S.O",
  "Kosala S.O",
  "Mahabirod S.O",
  "Mahimagadi S.O",
  "Marthapur S.O",
  "Mathakargola S.O",
  "Meramandali S.O",
  "Nalconagar S.O",
  "Nehru Satabdi Nagar(Bharatpu) S.O",
  "P.T.C.Angul S.O",
  "Pabitranagar S.O",
  "Pallahara S.O",
  "Parjang S.O",
  "Rajkishorenagar S.O",
  "Rasol S.O",
  "Rengali Dam Site S.O",
  "Samal Barrage Township S.O",
  "Talcher S.O",
  "Talcher Thermal S.O",
  "Talcher Town S.O",
  "Talmul S.O",
  "Vikrampur S.O",
];
